DATA:
  prompt: "A cute corgi dog with a big smile"
  uncond_prompt: ""
  image_path: "images/input/corgi.jpg"
  output_dir: "images/output"

  width: 512
  height: 512

TOKENIZER:
  vocab_file_path: "data/vocab.json"
  merges_file_path: "data/merges.txt"
  max_length: 77

MODEL:
  mode: "text_to_image"               # 'image_to_image, 'text_to_image', 'impaint'
  device: "cuda"
  idle_device: "cpu"

  ckpt_path: "data/v1-5-pruned-emaonly.ckpt"
  
  downsampling_ratio: 8
  num_inference_steps: 2
  num_train_steps: 1000

  beta_start: 0.00085
  beta_end: 0.0120

  vae_scale: 0.18215
  do_cfg: True                          # If to use classifier-free guidance
  cfg_scale: 8                          # min: 1, max: 14
  strength: 0.4          # 0-1          # If image_to_image, strength is the weight of the guidance loss
